#ifndef GUARD_CONSTANTS_TIME_H
#define GUARD_CONSTANTS_TIME_H

#define MAX_YEARS 32
#define MAX_MONTHS 12
#define MAX_DAYS_OF_WEEK 7
#define MAX_HOURS 24
#define MAX_MINUTES 5
#define MAX_SECONDS 60
#define TOTAL_SECONDS_IN_HOUR MAX_MINUTES * MAX_SECONDS

#define DAY_MONDAY 0
#define DAY_TUESDAY 1
#define DAY_WEDNESDAY 2
#define DAY_THURSDAY 3
#define DAY_FRIDAY 4
#define DAY_SATURDAY 5
#define DAY_SUNDAY 6

#define MONTH_JANUARY 0
#define MONTH_FEBRUARY 1
#define MONTH_MARCH 2
#define MONTH_APRIL 3
#define MONTH_MAY 4
#define MONTH_JUNE 5
#define MONTH_JULY 6
#define MONTH_AUGUST 7
#define MONTH_SEPTEMBER 8
#define MONTH_OCTOBER 9
#define MONTH_NOVEMBER 10
#define MONTH_DECEMBER 11

#define DN_MIDNIGHT 0
#define DN_NIGHT 1
#define DN_DAWN 2
#define DN_DAY 3
#define DN_MIDDAY 4
#define DN_DUSK 5

#endif //GUARD_CONSTANTS_TIME_H
